"""Configuration file handling for .tally-config.toml."""

from __future__ import annotations

import tomllib
from pathlib import Path

CONFIG_FILENAME = '.tally-config.toml'


def find_config(root: Path) -> Path | None:
    """Search for .tally-config.toml starting at *root* and walking up.

    Returns the first config file found, or None.
    """
    current = root.resolve()
    while True:
        config_path = current / CONFIG_FILENAME
        if config_path.is_file():
            return config_path
        parent = current.parent
        if parent == current:
            return None
        current = parent


def load_config(config_path: Path) -> set[str]:
    """Load a .tally-config.toml and return excluded directory paths (relative to project root)."""
    with open(config_path, 'rb') as f:
        data = tomllib.load(f)
    dirs = data.get('exclude', {}).get('directories', [])
    return set(dirs)


def save_config(config_path: Path, excluded_dirs: set[str]) -> None:
    """Write a .tally-config.toml file. Sorts directories for deterministic output."""
    lines = [
        '# Generated by tallyman. Edit manually or re-run: tallyman --setup',
        '',
        '[exclude]',
        'directories = [',
    ]
    for d in sorted(excluded_dirs):
        lines.append(f'    "{d}",')
    lines.append(']')
    lines.append('')
    config_path.write_text('\n'.join(lines), encoding='utf-8')
